# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-10 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lugar',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='organizador',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='fecha',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
