# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-10 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20160910_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='posts',
        ),
        migrations.AddField(
            model_name='post',
            name='categoria',
            field=models.ManyToManyField(related_name='categorias', to='posts.Categoria'),
        ),
    ]
